global:
  imagePullPolicy: IfNotPresent

moneroCluster:
  service:
    name: monero
  image: 
    repo: samnco
    name: xmrminer
    dockerTag: 0.1.2
  settings:
    clusterName: ob
    pool: xmrminer
    nodes: 3
    workersPerNode: 1
    cpusPerWorker: 5
    gpuComplexity: 1
    username: samnco@gmail.com
  configMap: |-
    "cpu_thread_num" : 5,
    "cpu_threads_conf" : [ 
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },],
    "gpu_threads_conf" : [
      { "index" : 0, "threads" : 64, "blocks" : 30, "bfactor" : 6, "bsleep" :  25, "affine_to_cpu" : false},
     ],
    "pool_address" : "xmr-eu.dwarfpool.com:8050",
    "wallet_address" : "4GdoN7NCTi8a5gZug7PrwZNKjvHFmKeV11L6pNJPgj5QNEHsN6eeX3DaAQFwZ1ufD4LYCZKArktt113W7QjWvQ7CW9YZRapBW6vAuZ73md",
    "pool_password" : "x",
    "use_tls" : false,
    "tls_secure_algo" : true,
    "tls_fingerprint" : "",
    "call_timeout" : 10,
    "retry_time" : 10,
    "giveup_limit" : 0,
    "verbose_level" : 4,
    "h_print_time" : 60,
    "output_file" : "",
    "httpd_port" : 3000,
    "prefer_ipv4" : true,


