global:
  imagePullPolicy: IfNotPresent

moneroCluster:
  service:
    name: monero
  image: 
    repo: samnco
    name: xmrminer
    dockerTag: 0.1.4
  settings:
    replicaCount: 150
    gpuType: nvidia
    nvVersion: 387
    nodeSelector: GeForce-GTX-1060-6GB
  resources:
    # Only add CPU and Memory in here, nvidia GPUs are part of the model already. 
    requests: 
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 2048Mi      
  configMap: |-
    "pool_list" : [ { 
      "pool_address" : "pool.supportxmr.com:5555",
      "wallet_address" : "4GdoN7NCTi8a5gZug7PrwZNKjvHFmKeV11L6pNJPgj5QNEHsN6eeX3DaAQFwZ1ufD4LYCZKArktt113W7QjWvQ7CW9YZRapBW6vAuZ73md",
      "pool_password" : "x",
      "use_tls" : false,
      "tls_fingerprint" : "",
      "use_nicehash": false,
      "pool_weight": 1000,
    } ],
    "currency" : "monero",
    "call_timeout" : 10,
    "retry_time" : 30,
    "giveup_limit" : 0,
    "verbose_level" : 4,
    "print_motd" : true,
    "h_print_time" : 60,
    "aes_override" : null,
    "use_slow_memory" : "warn",
    "tls_secure_algo" : true,
    "daemon_mode" : false,
    "flush_stdout" : false,
    "output_file" : "",
    "httpd_port" : 3000,
    "http_login" : "",
    "http_pass" : "",
    "prefer_ipv4" : true,


serviceMonitor:
  enable: false
  labels: 
    - name: demo
      value: autoscaling

hpa:
  enable: false 
  apiVersion: v2beta1
  minReplicas: 2
  maxReplicas: 10
  metricName: cpu_remaining_capacity
  targetValue: 100

