apiVersion: extensions/{{- .Values.service.version }}
kind: Deployment
metadata:
  labels:
    app: {{ template "custom-metrics-apiserver.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "custom-metrics-apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "custom-metrics-apiserver.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "custom-metrics-apiserver.fullname" . }}
      name: {{ template "custom-metrics-apiserver.fullname" . }}
    spec:
      {{ if .Values.rbac.install -}}
      serviceAccountName: {{ template "custom-metrics-apiserver.fullname" . }}
      {{- end }}
      containers:
      - name: {{ template "custom-metrics-apiserver.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{ if .Values.service.tls.enable -}}
        - --secure-port={{ .Values.service.internalPort }}
        - --tls-cert-file=/var/run/serving-cert/tls.crt
        - --tls-private-key-file=/var/run/serving-cert/tls.key
        {{- end }}
        {{ if eq .Values.service.authentication.method "kubeconfig" -}}
        - --authentication-kubeconfig=/var/run/kubeconfig/kubeconfig
        {{- end }}
        - --logtostderr=true
        - --prometheus-url={{- .Values.prometheus.service.url -}}:{{- .Values.prometheus.service.port }}
        - --metrics-relist-interval=30s
        - --rate-interval=5m
        - --v=10
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        {{ if .Values.service.tls.enable -}}
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: true
        {{- end }}
        {{ if eq .Values.service.authentication.method "kubeconfig" -}}
        - mountPath: /var/run/kubeconfig
          name: kubeconfig
          readOnly: true
        {{- end }}
      volumes:
      {{ if .Values.service.tls.enable -}}
      - name: volume-serving-cert
        secret:
          secretName: {{ template "custom-metrics-apiserver.certname" . }}
      {{- end }}
      {{ if eq .Values.service.authentication.method "kubeconfig" -}}
      - name: kubeconfig
        secret:
          secretName: {{ template "custom-metrics-apiserver.kubeconfig" . }}
      {{- end }}
