{{- if .Values.rbac.install -}}
apiVersion: rbac.authorization.k8s.io/{{- .Values.rbac.apiVersion }}
kind: ClusterRoleBinding
metadata:
  name: custom-metrics-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-resource-reader
subjects:
- kind: ServiceAccount
  name: {{ template "custom-metrics-apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}