---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostDataDirPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
